### ISSUE TITLE
Error "Invalid import file" while importing workspace json

### ISSUE THREAD

**Issue by bennyevangelista** [flawiddsouza/Restfox#177]
I'm used to backup and restore entire Restfox application, recently I tried exporting a single workspace, but importing the resulting json file in a new workspace always ends in "invalid import file given". I didn't find anyone reporting a similar issue, so I'm feeling a bit...dummy :) Am I missing something?
![restfox](https://github.com/flawiddsouza/Restfox/assets/15796341/9df5216a-e1dd-47c7-a87c-0af919f21e04)

**Comment by flawiddsouza** [comment]
Hey, your backup is correct but this is the wrong place to import it.

Follow these steps:
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/9c18b593-abf1-4eb6-9714-ca747676ef83)
![image](https://github.com/flawiddsouza/Restfox/assets/10164500/ac8bd746-ffe3-48c8-9423-b4081a2b0731)

A backup taken in backup & restore can only be restored through the same dialog as it's a full application backup. The import option you're trying to use is specifically for importing a single exported workspace.

**Comment by bennyevangelista** [comment]
Probably I didn't explain myself: I usually do a full backup/restore (and it works fine), but today I tried exporting a **single workspace** (from inside the workspace -> export), then importing it in another workspace, and got the error. Maybe the workspace is too big? I tried with a new one, only one request in it, and importing works fine.

**Comment by flawiddsouza** [comment]
Oh. Then that's actually pretty odd. We'll have to debug. Press Ctrl + Shift + I to open Devtools. Try to import your export and see if you see any errors in the console tab of devtools. That could help us pinpoint the issue.

**Comment by bennyevangelista** [comment]
I'll give it try...as soon as I'm back from my week off 😁 many thanks!

**Comment by bennyevangelista** [comment]
HI, I'm back :) When importing the workspace file the console shows the error:

> TypeError: Cannot read properties of undefined (reading 'environment') at Proxy.importFile (index-e2a36f0b.js:863:113122)

I tried debugging but I'm not a javascript developer unfortunately :(

![err](https://github.com/user-attachments/assets/2364a47d-dd6b-4e94-86b2-65d981f04982)

**Comment by bennyevangelista** [comment]
I just noticed that while the import fails, it correctly imports all the environments in the json file. Maybe it's something related to the "Default" environment that is missing in the workspace I'm trying to import? After the error I tried adding a new environment called "Default" and after that import worked.

**Comment by flawiddsouza** [comment]
Weird. That shouldn't be happening. Is there some way you can provide the broken export? By commenting out or clearing all the senstive url and details? That would be really helpful in debugging and fixing the issue from my side.

**Comment by flawiddsouza** [comment]
@bennyevangelista The above is not needed. I was able to recreate the issue thanks to your information. I removed the Default environment before exporting and the import failed with the same error as yours. I should be able to fix this.

**Comment by bennyevangelista** [comment]
Great, thanks!

**Comment by flawiddsouza** [comment]
Hi @bennyevangelista, I've fixed the issue and it's deployed to https://restfox.dev. You can test your import there. I'll do a desktop release pretty soon.

**Comment by bennyevangelista** [comment]
great, it works! thanks

**Comment by Feryhl** [comment]
Hi @bennyevangelista, is the desktop release already available?

**Comment by bennyevangelista** [comment]
Yes, fix was included a couple of releases ago

**Comment by Feryhl** [comment]
@bennyevangelista i also thought so!! I have the v0.25.0 (472047b) desktop App version running and the problem is still present but meanwhile, i can import the file on restfox.dev/ without issues.

**Comment by flawiddsouza** [comment]
Hi @Feryhl, this seems like a new issue. Are you also getting the same error "Invalid Import file"?

To debug, let's do this.
1) Open the Restfox app
2) Open Devtools using Ctrl + Shift + I
3) Try importing your file, see what error shows up in the console. This will help us debug your issue.

**Comment by Feryhl** [comment]
Hi @flawiddsouza, here is error that showed up in the console:
![Screenshot Error](https://github.com/user-attachments/assets/8400028d-f432-4223-b91d-e17233fc6313)

I hope it helps!

**Comment by flawiddsouza** [comment]
Oh wait, I see you're try to import a postman collection. This issue is not related to that. But it does seem like a new bug. Let me create a new issue from comment and we can continue from that.
